// PODMIEŃ "TUTAJ_WKLEJ_CLIENT_ID" ORAZ "TUTAJ_WKLEJ_TOKEN_API" - NA POPRAWNY CLIENT ID ORAZ TOKEN WYGENEROWANY W SHOPERZE
// URUCHOM RAZ TEN SKRYPT W APLIKACJI SCRIPTABLE, ZEBY ZAPISAC DANE LOGOWANIA W APLIKACJI
// ZAWSZE Z POZIOMU SHOPERA MOZESZ ZMIENIĆ TE DANE, A SCRIPTABLE STRACI DOSTĘP DO ODCZYTU DANYCH SPRZEDAŻY, DO MOMENTU PONOWNEGO URUCHOMIENIA TEGO SKRYPTU Z AKTUALNYMI DANYMI


Keychain.set("shoper_client_id", "TUTAJ_WKLEJ_CLIENT_ID")
Keychain.set("shoper_api_token", "TUTAJ_WKLEJ_TOKEN_API")
